services:
  neo4j:
    image: neo4j:5-community
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-principlegraph}
    volumes:
      - neo4j_data:/data
      # - ./src/principle_graph/data/neo4j-schema.cypher:/var/lib/neo4j/import/neo4j-schema.cypher:rw

volumes:
  neo4j_data:
